from pydantic import BaseModel, Field, validator
from typing import Optional
from datetime import date, datetime

class ExpenseCreate(BaseModel):
    idempotency_key: str = Field(..., description="UUID generated by the client to prevent duplicate submissions")
    amount: float = Field(..., gt=0, description="Expense amount must be positive")
    category: str = Field(..., min_length=1, max_length=50)
    description: str = Field(..., max_length=255)
    date: date
    
class ExpenseOut(BaseModel):
    id: int
    user_id: str
    idempotency_key: str
    amount: float
    category: str
    description: str
    date: date
    created_at: datetime
    
    class Config:
        from_attributes = True
